In [1]:
import torch

# Creating a tensor
tensor_example = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Displaying basic properties of tensors
print(f"Shape of tensor: {tensor_example.shape}")
print(f"Data type of tensor: {tensor_example.dtype}")
print(tensor_example)

Shape of tensor: torch.Size([2, 3])
Data type of tensor: torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [2]:
import torch

# Tensor to be modified
tensor_example = torch.tensor([[1, 2, 3], [4, 5, 6],[8,9,0]])

# Displaying basic properties of tensors
print(f"Shape of tensor: {tensor_example.shape}")
print(f"Data type of tensor: {tensor_example.dtype}")
print(tensor_example)

Shape of tensor: torch.Size([3, 3])
Data type of tensor: torch.int64
tensor([[1, 2, 3],
        [4, 5, 6],
        [8, 9, 0]])


In [1]:
import torch

# Creating three tensors
tensor_a = torch.tensor([[1, 2], [3, 4]], dtype=torch.int32) # 2x2 tensor
tensor_b = torch.tensor([[5, 6], [7, 8]], dtype=torch.int32) # 2x2 tensor
tensor_c = torch.tensor([[1], [2]], dtype=torch.int32) # 2x1 tensor

# Addition
tensor_sum = torch.add(tensor_a, tensor_b)
print(f"Tensor Addition:\n{tensor_sum}\n")

# Element-wise Multiplication
tensor_product = torch.mul(tensor_a, tensor_b)
print(f"Element-wise Multiplication:\n{tensor_product}\n")

# Matrix Multiplication 
tensor_matmul = torch.matmul(tensor_a, tensor_c)
print(f"Matrix Multiplication:\n{tensor_matmul}\n")

# Broadcasted Addition (Tensor + scalar)
tensor_add_scalar = tensor_a + 5
print(f"Broadcasted Addition (Adding scalar value):\n{tensor_add_scalar}\n")

# Broadcasted Addition between tensors of different shapes: 
broadcasted_sum = tensor_a + tensor_c
print(f"Broadcasted Addition: \n{broadcasted_sum}\n")

# Broadcasted Multiplication between tensors of different shapes:
broadcasted_mul = tensor_a * tensor_c
print(f"Broadcasted Multiplication: \n{broadcasted_mul}\n")

Tensor Addition:
tensor([[ 6,  8],
        [10, 12]], dtype=torch.int32)

Element-wise Multiplication:
tensor([[ 5, 12],
        [21, 32]], dtype=torch.int32)

Matrix Multiplication:
tensor([[ 5],
        [11]], dtype=torch.int32)

Broadcasted Addition (Adding scalar value):
tensor([[6, 7],
        [8, 9]], dtype=torch.int32)

Broadcasted Addition: 
tensor([[2, 3],
        [5, 6]], dtype=torch.int32)

Broadcasted Multiplication: 
tensor([[1, 2],
        [6, 8]], dtype=torch.int32)

