In [1]:
import torch

# Creating a tensor
tensor_example = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Displaying basic properties of tensors
print(f"Shape of tensor: {tensor_example.shape}")
print(f"Data type of tensor: {tensor_example.dtype}")
print(tensor_example)

Shape of tensor: torch.Size([2, 3])
Data type of tensor: torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [2]:
import torch

# Tensor to be modified
tensor_example = torch.tensor([[1, 2, 3], [4, 5, 6],[8,9,0]])

# Displaying basic properties of tensors
print(f"Shape of tensor: {tensor_example.shape}")
print(f"Data type of tensor: {tensor_example.dtype}")
print(tensor_example)

Shape of tensor: torch.Size([3, 3])
Data type of tensor: torch.int64
tensor([[1, 2, 3],
        [4, 5, 6],
        [8, 9, 0]])


In [1]:
import torch

# Creating three tensors
tensor_a = torch.tensor([[1, 2], [3, 4]], dtype=torch.int32) # 2x2 tensor
tensor_b = torch.tensor([[5, 6], [7, 8]], dtype=torch.int32) # 2x2 tensor
tensor_c = torch.tensor([[1], [2]], dtype=torch.int32) # 2x1 tensor

# Addition
tensor_sum = torch.add(tensor_a, tensor_b)
print(f"Tensor Addition:\n{tensor_sum}\n")

# Element-wise Multiplication
tensor_product = torch.mul(tensor_a, tensor_b)
print(f"Element-wise Multiplication:\n{tensor_product}\n")

# Matrix Multiplication 
tensor_matmul = torch.matmul(tensor_a, tensor_c)
print(f"Matrix Multiplication:\n{tensor_matmul}\n")

# Broadcasted Addition (Tensor + scalar)
tensor_add_scalar = tensor_a + 5
print(f"Broadcasted Addition (Adding scalar value):\n{tensor_add_scalar}\n")

# Broadcasted Addition between tensors of different shapes: 
broadcasted_sum = tensor_a + tensor_c
print(f"Broadcasted Addition: \n{broadcasted_sum}\n")

# Broadcasted Multiplication between tensors of different shapes:
broadcasted_mul = tensor_a * tensor_c
print(f"Broadcasted Multiplication: \n{broadcasted_mul}\n")

Tensor Addition:
tensor([[ 6,  8],
        [10, 12]], dtype=torch.int32)

Element-wise Multiplication:
tensor([[ 5, 12],
        [21, 32]], dtype=torch.int32)

Matrix Multiplication:
tensor([[ 5],
        [11]], dtype=torch.int32)

Broadcasted Addition (Adding scalar value):
tensor([[6, 7],
        [8, 9]], dtype=torch.int32)

Broadcasted Addition: 
tensor([[2, 3],
        [5, 6]], dtype=torch.int32)

Broadcasted Multiplication: 
tensor([[1, 2],
        [6, 8]], dtype=torch.int32)



In [1]:
import torch

# Creating three tensors
heroes = torch.tensor([[2, 3], [4, 5]], dtype=torch.int32) # 2x2 tensor
villains = torch.tensor([[7, 8], [9, 10]], dtype=torch.int32) # 2x2 tensor
sidekicks = torch.tensor([[2], [3]], dtype=torch.int32) # 2x1 tensor

# Addition
combined_power = torch.add(heroes, villains)
print(f"Combined Power:\n{combined_power}\n")

# Element-wise Multiplication
power_product = torch.mul(heroes, villains)
print(f"Power Product:\n{power_product}\n")

# Matrix Multiplication 
team_effectiveness = torch.matmul(heroes, sidekicks)
print(f"Team Effectiveness:\n{team_effectiveness}\n")

# TODO: Add code for broadcasted addition (tensor + scalar)
tensor_add_scalar = heroes + 5
print(f"Broadcasted Addition (Adding scalar value):\n{tensor_add_scalar}\n")
# TODO: Add code for broadcasted addition between tensors of different shapes (heroes + sidekicks)
broadcasted_sum = villains + sidekicks
print(f"Broadcasted Addition: \n{broadcasted_sum}\n")
# TODO: Add code for broadcasted multiplication between tensors of different shapes (heroes * sidekicks)
broadcasted_mul = heroes * sidekicks
print(f"Broadcasted Multiplication: \n{broadcasted_mul}\n")

Combined Power:
tensor([[ 9, 11],
        [13, 15]], dtype=torch.int32)

Power Product:
tensor([[14, 24],
        [36, 50]], dtype=torch.int32)

Team Effectiveness:
tensor([[13],
        [23]], dtype=torch.int32)

Broadcasted Addition (Adding scalar value):
tensor([[ 7,  8],
        [ 9, 10]], dtype=torch.int32)

Broadcasted Addition: 
tensor([[ 9, 10],
        [12, 13]], dtype=torch.int32)

Broadcasted Multiplication: 
tensor([[ 4,  6],
        [12, 15]], dtype=torch.int32)



In [2]:
import torch

# Creating a tensor for manipulation
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reshape the tensor
reshaped_tensor = tensor_a.view(3, 2)

# Flatten the tensor
flattened_tensor = tensor_a.view(-1)

print(f"Original Tensor:\n{tensor_a}\n")
print(f"Reshaped Tensor:\n{reshaped_tensor}\n")
print(f"Flattened Tensor:\n{flattened_tensor}")

Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Reshaped Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Flattened Tensor:
tensor([1, 2, 3, 4, 5, 6])
