In [6]:
import torch
import numpy as np
x= torch.rand(2,2)
print(x)

tensor([[0.9114, 0.3537],
        [0.8462, 0.2450]])


In [7]:
import torch 
X = torch.tensor([1,2,3,4,5,6,7,8], dtype=torch.float32)
Y = torch.tensor([2,4,6,8,10,12,14,16],dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32,requires_grad=True)

def forward(x):
    return w * x

def loss(y,y_pred):
    return((y_pred - y)**2).mean()
X_test = 5.0

print(f"Prediction befor training :F({X_test})={forward(X_test).item():.3f}")




Prediction befor training :F(5.0)=0.000


In [8]:
import torch
print(torch.cuda.is_available())
print(torch.rand(2,2))



False
tensor([[0.9342, 0.2024],
        [0.7319, 0.1319]])


In [9]:
torch.rand(2,2).max()
torch.rand(2,2).max().item()

0.756930410861969

In [10]:
torch.rand(2,2).min()
torch.rand(2,2).min().item()

0.002444446086883545

In [14]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [15]:
x = torch.randn(1,10)
prev_h = torch.randn(1,20)
W_h = torch.randn(20,20)
W_x = torch.randn(20,10)

i2h = torch.mm(W_x,x.t())
h2h = torch.mm(W_h,prev_h.t())

next_h = i2h + h2h
next_h = next_h.tanh()
loss = next_h.sum()
loss.backward

<bound method Tensor.backward of tensor(-3.3215)>